server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml # Path inside the container (maps to promtail_positions volume)

clients:
  - url: http://loki:3100/loki/api/v1/push # Loki service name from docker-compose

scrape_configs:
  - job_name: django-app
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters: # <<< Use this corrected format
          - name: label # Filter type is 'label'
            values:
              - "logging=promtail"    # Value is "key=value"
              - "application=django-rag" # Value is "key=value"
    relabel_configs:
      # Relabel Docker container labels to Loki labels
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      # Keep this relabeling rule to get the 'app' label in Loki
      - source_labels: ['__meta_docker_container_label_application']
        target_label: 'app'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

    pipeline_stages:
      # ... your pipeline stages remain the same ...
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message_content: message # Keep original message here
      - json:
          source: message_content
          expressions:
            query_id: "query_id || ''"
            response_length: "response_length || ''"
            kb_id: "kb_id || ''"
            model_used: "model_used || ''"
            reranker_used: "reranker_used || ''"
            retrieval_top_k: "retrieval_top_k || ''"
            reranker_top_k: "reranker_top_k || ''"
            docs_retrieved_count: "docs_retrieved_count || ''"
            docs_returned_count: "docs_returned_count || ''"
          drop_malformed: false
      - timestamp:
          source: timestamp
          format: ISO8601
      - labels:
          level:
          query_id:
          model_used:
          reranker_used:
          kb_id:
      - output:
          source: message_content