# Generated by Django 5.1.6 on 2025-04-24 10:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(db_index=True, help_text='Session ID for grouping queries', max_length=36)),
                ('user_query', models.TextField(help_text='Original user query')),
                ('llm_response', models.TextField(blank=True, help_text='Response from the LLM', null=True)),
                ('doc_tag', models.JSONField(blank=True, default=list, help_text='List of document tags for the query context')),
                ('file_paths', models.JSONField(default=list, help_text='List of file_path strings for retrieved document chunks')),
                ('model_used', models.CharField(blank=True, help_text='The LLM model used', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chat_id'], name='idx_chatquery_chat_id'), models.Index(fields=['doc_tag'], name='idx_chatquery_doc_tag'), models.Index(fields=['created_at'], name='idx_chatquery_created_at')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField(unique=True)),
                ('doc_tag', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('original_url', models.URLField(blank=True, help_text='Main source URL for the document', max_length=500, null=True)),
                ('chunk_url', models.URLField(blank=True, help_text='Permalink to the specific document chunk', max_length=500, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-inserted_at'],
                'indexes': [models.Index(fields=['doc_tag'], name='idx_documents_doc_tag')],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('helpful', 'Helpful'), ('unhelpful', 'Unhelpful'), ('false', 'False')], max_length=20)),
                ('feedback_text', models.TextField(blank=True, help_text='Optional additional comments on the LLM response', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(help_text='The query this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='logius.chatquery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
