# Generated by Django 5.1.6 on 2025-04-16 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_query', models.TextField(help_text='Original user query')),
                ('enhanced_query', models.TextField(blank=True, help_text='Query enhanced using HyDE or query augmentation (if applicable)', null=True)),
                ('model_used', models.CharField(help_text='The LLM model used for processing', max_length=100)),
                ('additional_parameters', models.JSONField(blank=True, help_text='JSON object storing parameters such as use_hyde, use_augmentation, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField(unique=True)),
                ('doc_tag', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('original_url', models.URLField(blank=True, help_text='Main source URL for the document', max_length=500, null=True)),
                ('chunk_url', models.URLField(blank=True, help_text='Permalink to the specific document chunk', max_length=500, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-inserted_at'],
                'indexes': [models.Index(fields=['doc_tag'], name='idx_documents_doc_tag')],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('helpful', 'Helpful'), ('unhelpful', 'Unhelpful'), ('false', 'False')], max_length=20)),
                ('feedback_text', models.TextField(blank=True, help_text='Optional additional comments on the LLM response', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='logius.query')),
            ],
        ),
        migrations.CreateModel(
            name='QueryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrieval_score', models.FloatField(blank=True, help_text='Score from the vector retrieval process', null=True)),
                ('rank_position', models.PositiveIntegerField(blank=True, help_text='Ranking position in the retrieval set', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_queries', to='logius.document')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_documents', to='logius.query')),
            ],
            options={
                'ordering': ['rank_position'],
                'unique_together': {('query', 'document')},
            },
        ),
    ]
