# Generated by Django 5.1.6 on 2025-04-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logius', '0002_alter_feedback_options_chatquery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatquery',
            name='doc_tag',
            field=models.JSONField(blank=True, default=list, help_text='List of document tags for the query context'),
        ),
    ]
