# Generated by Django 5.1.6 on 2025-05-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logius', '0002_remove_chatquery_idx_chatquery_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatquery',
            name='final_doc_ids',
            field=models.JSONField(default=list, help_text='List of Qdrant point IDs of the final documents used for context in this turn, potentially becoming sticky memory for the next.'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(blank=True, help_text='Optional free-text comments from the user if implemented', null=True),
        ),
    ]
